export type AdminLocale = "fa" | "en" | "ar";

export function normalizeAdminLocale(locale?: string): AdminLocale {
  return locale === "en" || locale === "ar" ? locale : "fa";
}

const copy = {
  fa: {
    support: "پشتیبانی",
    categories: "مدیریت دسته‌بندی‌ها",
    categoriesDescription: "مدیریت دسته‌بندی‌های محصولات و ترجمه‌ها",
    addCategory: "دسته‌بندی جدید",
    totalUsers: "کل کاربران",
    activeUsers: "کاربران فعال",
    newUsersThisMonth: "کاربران جدید این ماه",
    adminUsers: "کاربران مدیریتی",
    searchUsers: "جستجو در کاربران...",
    allRoles: "همه نقش‌ها",
    customer: "مشتری",
    admin: "مدیر",
    superAdmin: "مدیر ارشد",
    addUser: "کاربر جدید",
    loadingUsers: "در حال بارگذاری کاربران...",
    products: "مدیریت محصولات",
    addProduct: "افزودن محصول",
    search: "جستجو",
    searchProducts: "جستجو در نام، SKU یا توضیحات...",
    category: "دسته‌بندی",
    allCategories: "همه دسته‌بندی‌ها",
    status: "وضعیت",
    all: "همه",
    active: "فعال",
    inactive: "غیرفعال",
    outOfStock: "ناموجود",
    lowStock: "کم موجودی",
    productList: "لیست محصولات",
    product: "محصول",
    of: "از",
    totalOrders: "کل سفارشات",
    pending: "در انتظار",
    processing: "در حال پردازش",
    totalRevenue: "کل درآمد",
    orderStatus: "وضعیت سفارش",
    paymentStatus: "وضعیت پرداخت",
    allStatuses: "همه وضعیت‌ها",
    confirmed: "تأیید شده",
    shipped: "ارسال شده",
    delivered: "تحویل شده",
    cancelled: "لغو شده",
    refunded: "بازپرداخت شده",
    paid: "پرداخت شده",
    failed: "ناموفق",
    partiallyRefunded: "بازپرداخت جزئی",
    dateRange: "بازه زمانی",
    generalSettings: "تنظیمات عمومی",
    emailSettings: "تنظیمات ایمیل",
    paymentSettings: "تنظیمات پرداخت",
    shippingMethods: "روش‌های ارسال",
    supportCenter: "مرکز پشتیبانی",
    supportDescription: "مدیریت تیکت‌ها و گفتگو با مشتریان",
    searchPlaceholder: "جستجو...",
    apply: "اعمال",
    loading: "در حال بارگذاری...",
    noTickets: "تیکتی یافت نشد.",
    selectTicket: "یک تیکت را انتخاب کنید.",
    replyPlaceholder: "پاسخ پشتیبانی...",
    internalNote: "یادداشت داخلی",
    sendReply: "ارسال پاسخ",
    open: "باز",
    pendingAdmin: "در انتظار پشتیبانی",
    pendingUser: "در انتظار مشتری",
    resolved: "حل‌شده",
    closed: "بسته",
    low: "کم",
    normal: "معمولی",
    high: "مهم",
    urgent: "فوری",
    order: "سفارش",
    checkingAccess: "در حال بررسی دسترسی...",
    unauthorized: "دسترسی غیرمجاز",
    unauthorizedDescription: "شما مجوز دسترسی به این بخش را ندارید.",
    backHome: "بازگشت به صفحه اصلی",
  },
  en: {
    support: "Support",
    categories: "Category Management",
    categoriesDescription: "Manage product categories and translations",
    addCategory: "Add category",
    totalUsers: "Total users",
    activeUsers: "Active users",
    newUsersThisMonth: "New users this month",
    adminUsers: "Administrative users",
    searchUsers: "Search users...",
    allRoles: "All roles",
    customer: "Customer",
    admin: "Admin",
    superAdmin: "Super Admin",
    addUser: "Add user",
    loadingUsers: "Loading users...",
    products: "Product Management",
    addProduct: "Add product",
    search: "Search",
    searchProducts: "Search name, SKU, or description...",
    category: "Category",
    allCategories: "All categories",
    status: "Status",
    all: "All",
    active: "Active",
    inactive: "Inactive",
    outOfStock: "Out of stock",
    lowStock: "Low stock",
    productList: "Products",
    product: "product",
    of: "of",
    totalOrders: "Total orders",
    pending: "Pending",
    processing: "Processing",
    totalRevenue: "Total revenue",
    orderStatus: "Order status",
    paymentStatus: "Payment status",
    allStatuses: "All statuses",
    confirmed: "Confirmed",
    shipped: "Shipped",
    delivered: "Delivered",
    cancelled: "Cancelled",
    refunded: "Refunded",
    paid: "Paid",
    failed: "Failed",
    partiallyRefunded: "Partially refunded",
    dateRange: "Date range",
    generalSettings: "General settings",
    emailSettings: "Email settings",
    paymentSettings: "Payment settings",
    shippingMethods: "Shipping methods",
    supportCenter: "Support Center",
    supportDescription: "Manage tickets and customer conversations",
    searchPlaceholder: "Search...",
    apply: "Apply",
    loading: "Loading...",
    noTickets: "No tickets found.",
    selectTicket: "Select a ticket.",
    replyPlaceholder: "Support reply...",
    internalNote: "Internal note",
    sendReply: "Send reply",
    open: "Open",
    pendingAdmin: "Waiting for support",
    pendingUser: "Waiting for customer",
    resolved: "Resolved",
    closed: "Closed",
    low: "Low",
    normal: "Normal",
    high: "High",
    urgent: "Urgent",
    order: "Order",
    checkingAccess: "Checking access...",
    unauthorized: "Unauthorized",
    unauthorizedDescription:
      "You do not have permission to access this section.",
    backHome: "Back to home",
  },
  ar: {
    support: "الدعم",
    categories: "إدارة الفئات",
    categoriesDescription: "إدارة فئات المنتجات وترجماتها",
    addCategory: "إضافة فئة",
    totalUsers: "إجمالي المستخدمين",
    activeUsers: "المستخدمون النشطون",
    newUsersThisMonth: "المستخدمون الجدد هذا الشهر",
    adminUsers: "المستخدمون الإداريون",
    searchUsers: "البحث في المستخدمين...",
    allRoles: "كل الأدوار",
    customer: "عميل",
    admin: "مدير",
    superAdmin: "مدير أعلى",
    addUser: "إضافة مستخدم",
    loadingUsers: "جار تحميل المستخدمين...",
    products: "إدارة المنتجات",
    addProduct: "إضافة منتج",
    search: "بحث",
    searchProducts: "ابحث بالاسم أو SKU أو الوصف...",
    category: "الفئة",
    allCategories: "كل الفئات",
    status: "الحالة",
    all: "الكل",
    active: "نشط",
    inactive: "غير نشط",
    outOfStock: "غير متوفر",
    lowStock: "مخزون منخفض",
    productList: "المنتجات",
    product: "منتج",
    of: "من",
    totalOrders: "إجمالي الطلبات",
    pending: "قيد الانتظار",
    processing: "قيد المعالجة",
    totalRevenue: "إجمالي الإيرادات",
    orderStatus: "حالة الطلب",
    paymentStatus: "حالة الدفع",
    allStatuses: "كل الحالات",
    confirmed: "مؤكد",
    shipped: "تم الشحن",
    delivered: "تم التسليم",
    cancelled: "ملغي",
    refunded: "مسترد",
    paid: "مدفوع",
    failed: "فشل",
    partiallyRefunded: "مسترد جزئياً",
    dateRange: "النطاق الزمني",
    generalSettings: "الإعدادات العامة",
    emailSettings: "إعدادات البريد",
    paymentSettings: "إعدادات الدفع",
    shippingMethods: "طرق الشحن",
    supportCenter: "مركز الدعم",
    supportDescription: "إدارة التذاكر ومحادثات العملاء",
    searchPlaceholder: "بحث...",
    apply: "تطبيق",
    loading: "جار التحميل...",
    noTickets: "لم يتم العثور على تذاكر.",
    selectTicket: "اختر تذكرة.",
    replyPlaceholder: "رد الدعم...",
    internalNote: "ملاحظة داخلية",
    sendReply: "إرسال الرد",
    open: "مفتوح",
    pendingAdmin: "بانتظار الدعم",
    pendingUser: "بانتظار العميل",
    resolved: "تم الحل",
    closed: "مغلق",
    low: "منخفض",
    normal: "عادي",
    high: "مرتفع",
    urgent: "عاجل",
    order: "الطلب",
    checkingAccess: "جار التحقق من الصلاحية...",
    unauthorized: "غير مصرح",
    unauthorizedDescription: "ليس لديك إذن للوصول إلى هذا القسم.",
    backHome: "العودة إلى الرئيسية",
  },
} as const;

export function getAdminCopy(locale?: string) {
  return copy[normalizeAdminLocale(locale)];
}
